name: linux
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        perl:
          - '5.16'
          - '5.20'
          - '5.26'
          - '5.38'
          - latest
        include:
          - { os: macos-latest, perl: '5.26' }
          - { os: macos-latest, perl: latest }

    name: 🐪 Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: perl -V
        run: perl -V
      - name: Set up perl
        run: |
          cpanm --notest --with-develop --installdeps .
          perl Build.PL
          ./Build build
      - name: Run tests 
        run: |
          TEST_SHARED=1 TEST_SUBREAPER=1 cover -test -report codecovbash
      - name: Upload coverage to ☂️ Codecov
        uses: codecov/codecov-action@v2
        if: matrix.perl == '5.30'
        with:
          file: cover_db/codecov.json
          fail_ci_if_error: true
          verbose: true
