name: Unit and integration tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        perl:
#          - '5.16'
#          - '5.20'
          - '5.26'
#          - '5.30'
#          - '5.34'
#          - '5.38'
#          - '5.40'
          - latest
        include:
          - os: macos-latest
            perl: '5.26'
          - os: macos-latest
            perl: latest
    name: 🐪 Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - name: Install Bash 4 and GNU sed on Mac
        if: matrix.os == 'macos-latest'
        run: |
          brew install bash
          brew install gnu-sed
          /bin/bash --version
          bash --version
          which bash

      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: perl -V
        run: perl -V
      - name: Set up perl
        run: |
          cpanm --with-feature=ci --installdeps --notest .
          perl Build.PL
          ./Build build
      - name: Run tests
        run: |
          for i in $(seq 1 100); do
          TEST_SHARED=1 TEST_SUBREAPER=1 prove -l -v t/01_run.t --merge
          done
